# Generated by Django 2.0.2 on 2018-03-24 08:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180323_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_pic',
            field=models.ImageField(null=True, upload_to='pic_folder/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 3, 24, 8, 54, 25, 257146, tzinfo=utc)),
        ),
    ]
