# Generated by Django 2.0.2 on 2018-03-24 09:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180324_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='model_pic',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 3, 24, 9, 8, 1, 402226, tzinfo=utc)),
        ),
    ]
