# Generated by Django 2.0.2 on 2018-03-24 09:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180324_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[(0, 'Electronics'), (1, 'HouseHold'), (2, 'Daily'), (3, 'Clothing')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 3, 24, 9, 35, 44, 682140, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='main/static/pic_folder/'),
        ),
    ]
